#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: app-name-placeholder-dev
      auth:
        workloadIdentity:
          clusterLocation: us-west1-a
          clusterName: app-name-placeholder-dev
          clusterProjectID: app-name-placeholder-dev
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
