#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-name-placeholder-main-tls-cert
  namespace: app-name-placeholder
spec:
  commonName: localhost
  secretName: app-name-placeholder-main-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - localhost
