#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name-placeholder-web
  namespace: app-name-placeholder
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: app-name-placeholder-web-container
          image: ghcr.io/registry-org-placeholder/app-name-placeholder-web:main
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 1Gi
              cpu: 100m
