apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tanka-cmp
  namespace: argocd
  annotations:
    app.kubernetes.io/part-of: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: tanka
    spec:
      init:
        command: [jb, install]
      generate:
        command: [sh, -c]
        args: ["echo 'DEBUG: ARGOCD_ENV_COMPONENT='$ARGOCD_ENV_COMPONENT && echo '--- ENV VARS ---' && env | grep ARGOCD && echo '--- END ENV ---' && exit 1"]
      discover:
        fileName: "./jsonnetfile.json"
      allowConcurrency: true
      lockRepo: false
