apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spezistudyplatform-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/WowSuchRicky/spezi-study-platform-infrastructure.git
    path: tanka/environments/production
    targetRevision: HEAD
    directory:
      jsonnet: {}
      include: argocd-apps.jsonnet
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
