apiVersion: v1
kind: Service
metadata:
  name: spezistudyplatform-frontend-service
  namespace: spezistudyplatform
spec:
  selector:
    app: spezistudyplatform-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: main
  type: ClusterIP