apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tanka-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: tanka
    spec:
      version: v1.0
      generate:
        command: ["tk", "show", "."]
      discover:
        fileName: "spec.json"
