apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: tanka
      init:
        command: [jb, install]
      generate:
        command: [sh, -c]
        args: ["tk show . --tla-str component=${ARGOCD_ENV_COMPONENT}"]
      discover:
        fileName: "spec.json"
