#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-config-cli
  namespace: app-name-placeholder
spec:
  template:
    metadata:
      labels:
        app: keycloak-config-cli
    spec:
      containers:
        - name: keycloak-config-cli
          env:
            - name: WEB_URL
              value: https://domain-placeholder
