#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-name-placeholder-db
  namespace: app-name-placeholder
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-2-bullseye
  instances: 1
  storage:
    size: 1Gi
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: app-name-placeholder
      owner: app-name-placeholder
      secret:
        name: app-name-placeholder-postgres-credentials
