#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-name-placeholder-postgres-credentials
  namespace: app-name-placeholder
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: app-name-placeholder-postgres-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: server-db-credentials
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: server-db-credentials
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
