#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-name-placeholder-web-config
  namespace: app-name-placeholder
data:
  VITE_API_BASE_PATH: https://localhost
  VITE_KEYCLOAK_URL: https://localhost/auth
  VITE_KEYCLOAK_REALM: app-name-placeholder
  VITE_KEYCLOAK_CLIENT_ID: app-name-placeholder-web
