#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: app-name-placeholder
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-db-credentials
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: keycloak-db-credentials
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
