---
- name: Provision GKE Cluster with Terraform
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Recommended to set this relative to the root of the repo and then run the playbook from the root as well.
    terraform_relative_path: "rendered_infra/tofu/gke"
    terraform_directory: "{{ terraform_relative_path | realpath }}"

    gcp_project_id: "{{ spezi_service_gcp_project_id }}"

    # TODO: should just use the var for this instead of setting it here.
    gcp_zone: "us-west1-c"

    gke_cluster_name: "{{spezi_service_gcp_project_id}}-gke"

    terraform_backend_config:
      bucket: "{{ spezi_service_name }}-tf-state-prod"
      prefix: "gke/{{ spezi_service_name }}"

  roles:
    - provision_gke
