#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-name-placeholder-server-config
  namespace: app-name-placeholder
data:
  DATABASE_HOST: app-name-placeholder-db-rw
  DATABASE_NAME: app-name-placeholder
  KEYCLOAK_URL: http://keycloak.app-name-placeholder.svc.cluster.local/auth
  KEYCLOAK_REALM: app-name-placeholder
  KEYCLOAK_CLIENT_ID: app-name-placeholder-server
  KEYCLOAK_RESEARCHER_ROLE: app-name-placeholder-researcher
  KEYCLOAK_PARTICIPANT_ROLE: app-name-placeholder-participant
  APP_ENVIRONMENT: development
