#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name-placeholder-server
  namespace: app-name-placeholder
  labels:
    app: app-name-placeholder-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-name-placeholder-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-name-placeholder-server
    spec:
      serviceAccountName: app-name-placeholder-server
      initContainers:
        - name: app-name-placeholder-server-migrate
          image: ghcr.io/registry-org-placeholder/app-name-placeholder-server:latest
          imagePullPolicy: Always
          command: ["./app-name-pascal-placeholderServer", "migrate", "--yes"]
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: app-name-placeholder-server-config
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-name-placeholder-postgres-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-name-placeholder-postgres-credentials
                  key: password
      containers:
        - name: app-name-placeholder-server-container
          image: ghcr.io/registry-org-placeholder/app-name-placeholder-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: app-name-placeholder-server-config
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-name-placeholder-postgres-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-name-placeholder-postgres-credentials
                  key: password
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-name-placeholder-server-secret
                  key: KEYCLOAK_CLIENT_SECRET
          startupProbe:
            httpGet:
              path: /api/v0/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /api/v0/health
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v0/health
              port: 8080
            periodSeconds: 15
