#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-name-placeholder-server-secret
  namespace: app-name-placeholder
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: app-name-placeholder-server-secret
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: server-credentials
        property: KEYCLOAK_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
