#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

apiVersion: v1
kind: Service
metadata:
  name: app-name-placeholder-server-service
  namespace: app-name-placeholder
spec:
  selector:
    app: app-name-placeholder-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
